apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuaXNodWt1bWFyaTE3IiwicGFzc3dvcmQiOiJkY2tyX3BhdF9HT2kzX0dzT1htanR4VlNMbVd3Q2luaW1VY2siLCJlbWFpbCI6ImNzZS4yNGJjc2wyOEBzaWxpY29uLmFjLmluIiwiYXV0aCI6ImJtbHphSFZyZFcxaGNta3hOenBrWTJ0eVgzQmhkRjlIVDJrelgwZHpUMWh0YW5SNFZsTk1iVmQzUTJsdWFXMVZZMnM9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
