---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgABu/A1Y6T+pHtEFtrkJ30jWIWkal3Fp9q1ee8lVmyDqUGhTnfL/73nIbZFc3rJ87LjSiZ3ADLCtGiK/zVdnDwT+PQUuQuShBRF/WHUPZqiwn3waTtRA0MG469fFbMjtKJX9CMd4G2xti+yh7LWA/CNx1RX62jP2ESYnuROXnCQFJNT2PaTmFoev4wBs8XZQOEX5KO9IZh06FMTClp9YBxSlay4q/PwZ/Dy7BSerIbiF3Oo4/R/FIH7aDejSDtfiK+wmqYaWCT6I6bEcuwxatYrVJcJ2X6HwC3GtuIYHxNlQx9wPU2A0uf7mTHHEfEM+fgv5NgAhPOQ0LhVnV0uA9sTim3gHjb43qD3DTmsL+671v3HTqAj+1XM0cg/X3AyxAc9IKNRINnh+2D2LpFHDtSl5jV1E/BIE0Y/isPLv4im/0hGX+Maq3QpgQn1BLOUyBvWvSbiT74oGJ5PL2aNmyEztsapgtTWQFjblQz8KBA761eJ2iWSWO05CUpM/rRX1FeLF1e8JB0etkkiD4Px9KjdrLGt4PmrcXXepK4CYxLwMSnZwi6ErNq1IMw+EgRmnagIlDDXk4fKzFRRygbIm7o8oI1snpJ3v9v0ByZrBYZTYi02wxrnr6q9Xy+zLx2pFBEO4VtaAlTMwQJHPbUL2hp1rA61fb5UbPJ1Zq1SpLxXkxBBMHAdBXeNiuNfuEXJ2MxY8E8cFD5KTpB9DGGDfKcKvTRvI17IZKSQPdbzXRsarjI28eJpwUaSiTwo8jh+HrNd+rntH0mekuWXz6LnkBhARveAupUZzWRGxANnScB79ir/Jvl+aS5VkKjUgDrsr+mR2Ze7NK47bEMGCjXX/HNUQvzJy2E37jty4EXTmEIxKCa1yqFY4lUwwQFl6CbiH9q1uTad0NCPLP/eAIcKjuWP06EoP6kMjvZuSXi0lTWge4+Rru1XEFXBjIT/RZsUVfqlF8KOz5mA6dHdf/58u4KNfr5G9bSAFwhMF4GgGqBE8hwioSTMyHbK3U/V
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
